name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the vault-dev Docker image
      run: |
            docker build . --tag ghcr.io/gavrovski/vault-dev:latest
            docker push ghcr.io/gavrovski/vault-dev:latest

# this goes before the 'push' but now it's disabled
#            docker run ghcr.io/gavrovski/vault-dev:latest
